query allProducts(
  $categoryId: Int
  $filterStr: String
  $offset: Int
  $first: Int
) {
  allProducts(
    categoryId: $categoryId
    filterStr: $filterStr
    offset: $offset
    first: $first
  ) {
    filters {
      id
      name
      isColor
      hasChecked
      help
      type
      position
      values {
        id
        name
        isChecked
        filterValue
        help
        count
        position
        url
        value
      }
    }
    products {
      id
      name
      shortDescription
      brand {
        id
        name
      }
      category {
        id
        name
      }
      images(size: SM, withColorOnly: true) {
        id
        src
        width
        height
        colorName
        colorValue
        isTitle
      }
      subProducts {
        id
        article
        price
        oldPrice
        discount
      }
    }
    found
  }
}
