mutation addCartItem($subProductId: Int!) {
  addCartItem(subProductId: $subProductId) {
    cartItem {
      id
      price
      amount
      subProduct {
        id
        article
        price
        product {
          id
          name
          brand {
            id
            name
          }
          images {
            id
            src
            colorName
          }
        }
      }
      cart {
        id
        sessionid
        totalPrice
        amount
      }
    }
  }
}
