query filteredProducts($categoryId: Int, $filterStr: String) {
  filteredProducts(categoryId: $categoryId, filterStr: $filterStr) {
    found
    filters {
      id
      name
      isColor
      hasChecked
      help
      type
      position
      values {
        id
        name
        isChecked
        filterValue
        help
        count
        position
        url
        value
      }
    }
    products {
      id
    }
  }
}
